### ISSUE TITLE
/tables yield syntax error at or near "MATERIALIZED"

### ISSUE THREAD

**Issue by FGRibreau** [supabase/pg-api#51]
I gave a try to pg-api and requested `/tables` with the right headers, got a 500, looked at the log and found this:

```
throwing error error: syntax error at or near "MATERIALIZED"
    at Connection.parseE (/snapshot/pg-api/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/snapshot/pg-api/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/snapshot/pg-api/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 101,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '16',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1133',
  routine: 'scanner_yyerror'
}
```

It seems to be related with this part
https://github.com/supabase/pg-api/blob/ed5fa837504b66e18b3278905063e0891cd29e58/src/api/tables.ts#L128-L133

Note: the database does not have any tables (both in `public` and another user-created schema)

**Comment by kiwicopple** [comment]
Thanks for testing @FGRibreau ? I'm guessing you're on PG version less than 12?

Hey @soedirgo perhaps we can shift the code over to your `information_schema` optimizations and then remove the `MATERIALIZED` from this query?

**Comment by FGRibreau** [comment]
Ok, Removing "materialized" from "as materialized" works because I'm on postgresql v11.7.0 :)
